config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :toilets do
    resources :bookings, only: [:index, :show, :create, :edit, :update]
  end
  get "dashboard", to: "toilets#dashboard", as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :owner
  belongs_to :renter
  belongs_to :toilet
  validates :owner_id, presence: true
  validates :renter_id, presence: true
end

app/models/owner.rb
class Owner < User
  has_many :bookings, dependent: :destroy
  has_many :toilets, dependent: :destroy
  #validates :picture, presence: true

  def owner?
    true
  end
end

app/models/renter.rb
class Renter < User
  has_many :bookings
  has_many :toilets, through: :bookings

  def renter?
    true
  end
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :owner
  has_many :bookings, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :price, presence: true
  mount_uploader :picture, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def renter?
    false
  end
  def owner?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

 def configure_permitted_parameters
   # For additional fields in app/views/devise/registrations/new.html.erb
   devise_parameter_sanitizer.permit(:sign_up, keys: [:type])

   # For additional in app/views/devise/registrations/edit.html.erb
   # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
 end

# Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

# Uncomment when you *really understand* Pundit!
# rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
# def user_not_authorized
#   flash[:alert] = "You are not authorized to perform this action."
#   redirect_to(root_path)
# end

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(current_user.bookings)
    @toilet = Toilet.find(params[:toilet_id])
  end


  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    @markers = [
      {
        lat: session[:lat],
        lng: session[:lng],
      },
      {
        lat: @booking.toilet.latitude,
        lng: @booking.toilet.longitude,
      }
    ]
  end

  def create
    @booking = Booking.new
    authorize @booking
    @booking.toilet = Toilet.find(params[:toilet_id])
    @booking.renter = current_user
    @booking.owner = @booking.toilet.owner
    if @booking.save
      redirect_to toilet_booking_path(@booking.toilet, @booking)
    else
      render :show
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:review, :rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 skip_before_action :authenticate_user!, only: :home
  def home
    @naked = true
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_toilet, only: [:show, :edit, :update, :destroy]

  def index
    session[:lat] = params[:lat] if params[:lat]
    session[:lng] = params[:lng] if params[:lng]

    @toilets = policy_scope(Toilet.near([session[:lat], session[:lng]], 0.7) )

    @markers = [
      {
        lat: session[:lat],
        lng: session[:lng],
      }
    ]

    @toilets.inject(@markers) do |res, toilet|
      res << {
        lat: toilet.latitude,
        lng: toilet.longitude,
        icon: 'https://image.ibb.co/eSvbBU/toilet.png'
      }
    end
  end

  def dashboard
    @user = current_user
    authorize @user
    @bookings = @user.bookings
    @toilets = @user.toilets
    render "#{current_user.class.to_s.downcase}_dashboard"
    authorize @bookings
    authorize @toilets
  end

  def show
    @toilet = Toilet.find(params[:id])
    authorize @toilet
    @booking = Booking.new
    @booking.toilet = @toilet
  end

  def new
    @toilet = Toilet.new
    authorize @toilet
  end

  def create        # POST
    @toilet = Toilet.new(toilet_params)
    authorize @toilet
    @toilet.owner = current_user
    if @toilet.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @toilet = Toilet.find(params[:id])
    authorize @toilet
  end

  def update
    @toilet = Toilet.find(params[:id])
    authorize @toilet
    if @toilet.update(toilet_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @toilet = Toilet.find(params[:id])
    authorize @toilet
    @toilet.destroy
    redirect_to dashboard_path
  end

  private

  def set_toilet
    @toilet = Toilet.find(params[:id])
  end

  def toilet_params
    params.require(:toilet).permit(:title, :picture, :location, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="wrapper-form">

<div class="container-form">
  <h1>Add a review</h1>
    <div class="form-toilet">
        <%= simple_form_for [@booking.toilet, @booking] do |f| %>

          <%= f.input :review %>
          <%= f.input :rating, collection: 0..5%>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="wrapper-booking-details">

  <div class="container-booking-details">
    <h1>Bookings for <%= @toilet.title %></h1>
    <div class="cards-bookings_details">
      <div class="row">
      <% @bookings.each do |booking| %>

        <div class="col-xs-12 col-sm-12 card-bookings_details">
          <ul style="list-style-type:none">
          <li>
            <% if booking.review %>
            <p><strong>Booked:</strong> <%= booking.created_at %></p>
            <p><strong>By:</strong>      <%= booking.renter.email %></p>
            <p><strong>Review:</strong> <%= booking.review %></p>
            <p><strong>Rating:</strong> <%= booking.rating %>/5</p>
            <% else %>
            <p><strong>Booked:</strong> <%= booking.created_at %></p>
            <p><strong>By:</strong>      <%= booking.renter.email %></p>
            <p><strong>No review yet</strong></p>
            <p><strong>No rating yet</strong></p>
            <% end %>
          </li>
        </div>
      </ul>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/bookings/show.html.erb
<% if policy(Booking).show? %>
<h1 id="booking-title">Booking confirmed!</h1>
<div class="container">
  <% @markers[0][:icon] = image_path('poop.png') %>
  <div id="map" style="width: 100%; height: 500px;" data-markers="<%= @markers.to_json %>" data-route="true" setZoom="20">
</div>
<%= @booking.review %>
<% end %>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= image_tag 'toilet.png', height: 50 %>
  </div>
  <div class="footer-copyright">
    <p>Poop-It Technologies Inc. is a peer-to-peer toilet sharing, laboratory facility, and social networking company headquartered in Tel Aviv, Israel.</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <% if user_signed_in? %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">


      <!-- Links when logged in -->
             <%= link_to "Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% if current_user.class.to_s.downcase == "renter" %>
            <%= link_to "Toilets", toilets_path, class: "navbar-wagon-item navbar-wagon-link" %>
           <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-wagon-link', id: 'navbar-logout' do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
        <% end %>

        <% if current_user.class.to_s.downcase == "owner" %>
         <%= link_to "Add a toilet", new_toilet_path, class: "navbar-wagon-item navbar-wagon-link" %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-wagon-link', id: 'navbar-logout' do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
        <% end %>

      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>POOP-IT</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "layouts/navbar" unless @naked %>
    <%= render "layouts/flashes"%>
      <div class="body-content" style="min-height: 80vh";>
        <%= yield %>
      </div>

    <%= render "layouts/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_BROWSER_POOPIT']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://www.dailydot.com/wp-content/uploads/45d/6c/3994856e703d9f08c3d9ae96da892f6b.jpg');">
  <div class="banner-content">
      <h1>Poop-<em>it</em></h1>
    <div class="hero-banner-btn">
      <div class="circle">
        <%= link_to "#", id: "geolocate" do %>
        <div class="roll">
          <div class="sheetHolder">
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
          </div>
          <div class="paper">
            <div class="tube"></div>
          </div>
          <div class="paperHang">
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
            <div class="sheet"></div>
          </div>
        </div>
      </div>
      <% end %>
      <%= link_to "Login as a host", dashboard_path, class:"btn btn-primary", id:"host-btn" %>
    </div>
    <h4 class="pull-me">pull me</h4>
  </div>
</div>

<div class="home-services">
  <div class="services-container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 service-content">
        <p><%= image_tag 'service1.png' %></p>
        <h2>When you need it</h2>
        <p>In case of emergency when you're not at home</p>
      </div>
      <div class="col-xs-12 col-sm-4 service-content">
        <p><%= image_tag 'service2.png' %></p>
        <h2>Clean toilets</h2>
        <p>All our hosts are commited to keep their toilets clean and shiny</p>
      </div>
      <div class="col-xs-12 col-sm-4 service-content">
        <p><%= image_tag 'service3.png' %></p>
        <h2>Anywhere you are</h2>
        <p>Wherever you are, at any time of day and night, we find a toilet for you less than 800 meters away</p>
      </div>
    </div>
  </div>
</div>

<div class="home-description">
  <div class="description-container">
    <div class="description-picture">
      <%= image_tag "logo_out.png" %>
    </div>
    <div class="description-content">
      <h2>Why Poopt-it?</h2>
      <p>It started as a simple idea: An urgent need is something that everybody knows. We all have been in the situation where it happens when you are far from friendly facilities. There's still the option to walk in a restaurant, but not all of them will accept it, and you take the risk to end up in a dirty, unsafe toilet. That is why we’re working to make restroom facilitation safer and more accessible, helping people find clean and luxurious bathrooms quickly and affordably. Our hosts garantee the cleanliness of their toilet spots, as well as the constant resupply of toilet paper, soap, and the maintenance of all the facilities. <br><br>
      <strong>Wait no more, pull it now!</strong></p>
    </div>
  </div>
</div>

<div class="testimonal-wrap-margin">
  <div class="testimonal-wrap">
    <%= image_tag "testimonials-1.jpg" %>
    <div class="testimonal-content">
      <p>I have a very small bladder and need to pee all the f... time. Thanks to poop-it I can find a clean toilet to pee anytime, any where. It's always clean, there's always soap, I love it.</p>
    </div>

    <p class="testimonal-author">
      Jane Pee, small bladder
    </p>
  </div>

  <div class="testimonal-wrap">
    <%= image_tag "testimonials-2.jpg" %>
    <div class="testimonal-content">
      <p>My wife always yells at me after I poop because it smells too bad in the toilets. So I treat myself with a nice, stylish toilet with Poop-it, so I can poop in peace.</p>
    </div>
    <p class="testimonal-author">
      John Fart, scared of his wife
    </p>
  </div>
  <div class="testimonal-wrap">
    <%= image_tag "testimonials-3.jpg" %>
    <div class="testimonal-content">
      <p>After every meal, it's automatic, I need to poop. But I have a very busy life, I'm always on the roads, so thanks to poop-it, I can always find a nice toilet with magasines, relax and poop-it.</p>
    </div>
    <p class="testimonal-author">
      Kate Poop, pooper in chief
    </p>
  </div>
</div>

app/views/toilets/edit.html.erb
<div class="container-form">
<h1>Edit your toilet spot</h1>
  <div class="form-toilet">
    <%= simple_form_for(@toilet) do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :price %>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/toilets/index.html.erb
<div class="container-index">
  <div class="cards-container">
    <p><%= @toilets.size %> toilets found</p>
    <div class="row">
        <% @toilets.each do |toilet| %>
        <div class="col-xs-12 col-sm-4">
          <%= link_to toilet_path(toilet) do %>
          <div class="card card-index" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)),
             url('<%= cl_image_path toilet.picture %>')">
            <div class="card-description toilet-index">
              <p><%=toilet.title %></p>
              <p><%=toilet.price %> nis</p>
            </div>
          </div>
          <% end %>
        </div>

        <% end %>
    </div>
  </div>
  <% @markers[0][:icon] = image_path('poop.png') %>
  <div id="map" data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/toilets/new.html.erb
<div class="container-form">
<h1>Create your toilet spot</h1>
  <div class="row">
    <div class= "col-sm-3 offset-sm-3 form-toilet">
      <%= simple_form_for(@toilet) do |f| %>

        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :price %>
        <%= f.input :picture %>
        <%= f.input :picture_cache, as: :hidden %>
        <%= f.submit class: 'btn btn-primary form-group' %>
      <% end %>
    </div>
  </div>
</div>

app/views/toilets/owner_dashboard.html.erb
<div class="wrapper-dashboard">
  <div class="container-dashboard">
    <h1>Owner Dashboard</h1>
    <% @toilets.each do |toilet| %>
      <div class="message">
        <%= cl_image_tag toilet.picture, height: 50, width: 50, crop: :fill, class: "avatar-large" %>
        <div class="message-name">
          <h3><%= toilet.title %></h3>
          <p>created as of: <%= toilet.created_at %> </p>
        </div>
        <div class="message-body">
          <p><strong><%= toilet.location %> </strong></p>
          <p>
            <%= toilet.description %>
          </p>
        </div>
        <div class="message-status">
          <p class="status pending">Price</p>
          <p class="status pending"><%= toilet.price %>nis</p>
        </div>
        <div class="message-status">
          <p class="status pending"><%= link_to "bookings", toilet_bookings_path(toilet) %> </p>
          <p class="status pending"><%= link_to "update", edit_toilet_path(toilet) %></p>
          <p class="status pending"><%= link_to "delete", toilet_path(toilet), method: :delete %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/toilets/renter_dashboard.html.erb
<div class="wrapper-dashboard">
  <div class="container-dashboard">
    <h1>My bookings</h1>
    <% @bookings.each do |booking| %>
      <div class="message">
        <%= cl_image_tag booking.toilet.picture, height: 50, width: 50, crop: :fill, class: "avatar-large" %>
        <div class="message-name">
          <h3><%= booking.toilet.title %></h3>
          <p>created as of: <%= booking.created_at %> </p>
        </div>
        <div class="message-body">
          <p><strong>Review </strong></p>
          <% if booking.review %>
            <p>
              <%= booking.review%>
            </p>
          <% else %>
            <p> <%= link_to "Write a review", edit_toilet_booking_path(booking.toilet, booking)%></p>
          <% end %>
        </div>
        <div class="message-status">
          <p class="status pending">Rating</p>
          <% if booking.review %>
            <p class="status pending"><%= booking.rating %>/5</p>
          <% else %>
            <p><%= link_to "Write a review", edit_toilet_booking_path(booking.toilet, booking)%></p>
          <% end %>
        </div>
        <div class="message-status">
          <p class="status pending"><%= link_to "update review", edit_toilet_booking_path(booking.toilet, booking)%></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/toilets/show.html.erb
<div class="toilet-wrapper">
  <div class="toilet-container">
    <div class="container-flex">
      <div class="card toilet-pic" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)), url('<%= cl_image_path @toilet.picture %>')">
          <p><%= @toilet.title %></p>
          <p><strong><%= @toilet.price %>nis</strong></p>
      </div>
      <div class="go-link">
        <%= link_to "Go now!", toilet_bookings_path(@toilet), method: :post, class: "go-btn" if current_user.renter? %>
      </div>
    </div>
    <div class="grid-description">
      <p><strong>Description: </strong><%= @toilet.description %></p>
      <p><strong>Location: </strong><%= @toilet.location %></p>
    </div>
    <div class="back-search">
      <%= link_to "Back to search", toilets_path, class: "back-btn" %>
    </div>
  </div>
</div>